baseURL: http://merelinux.org/
languageCode: en-us
title:
theme: PaperMod
copyright: © 2021 Jeremy Huntwork
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: A lightweight Linux distribution using musl libc, pacman and s6.
  author: Jeremy Huntwork
  defaultTheme: dark
  disableThemeToggle: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  comments: false
  hidemeta: false

  homeInfoParams:
    Title: "\U0001F331 Mere Linux"
    Content: >
      A lightweight Linux distribution built around musl libc and s6.\

      \

      It currently uses pacman as the package manager, and llvm/clang as the
      toolchain and C compiler.\

      \

      Mere is still in its Alpha phase. If you are interested in helping to
      shape its direction, please visit the
      [Github Discussions](https://github.com/jhuntwork/merelinux/discussions/58)
      page and leave a comment.

  socialIcons:
    - name: github
      url: "https://github.com/jhuntwork/merelinux"

