baseURL: http://merelinux.org/
languageCode: en-us
title: "\U0001F331 Mere Linux"
theme: PaperMod
copyright: © 2021 Jeremy Huntwork
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: A lightweight Linux distribution using musl libc, pacman and s6.
  author: Jeremy Huntwork
  defaultTheme: dark
  disableThemeToggle: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  comments: false
  hidemeta: false

  homeInfoParams:
    Title: "Welcome!"
    Content: >
      Mere Linux is a lightweight Linux distribution built around
      [musl libc](https://musl.libc.org/) and
      [s6](https://skarnet.org/software/s6/) for system initialization and
      process supervision.\

      \

      It also uses [pacman](https://www.archlinux.org/pacman/)
      for package management, [busybox](https://busybox.net) for a suite of
      core utilities, and [llvm+clang](https://llvm.org) as the main C
      compiler and toolchain.\

      \

      Mere is still in its Alpha phase. If you are interested in helping to
      shape its direction, please visit the
      [Github Discussions](https://github.com/jhuntwork/merelinux/discussions/58)
      page and leave a comment.

  socialIcons:
    - name: github
      url: "https://github.com/jhuntwork/merelinux"
